<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<Product>RabbitOM</Product>
		<Authors>Rabbit Corp</Authors>
		<Description>Network communication library</Description>
		<Copyright>Copyright © 2026 RabbitOM</Copyright>
		<Trademark>RabbitOM™</Trademark>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
	</PropertyGroup>
</Project>
