<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<Product>RabbitOM.Player.Decoder.Api</Product>
		<Authors>Rabbit Corp</Authors>
		<Description>Api for managing video decoder</Description>
		<Copyright>Copyright © 2026 RabbitOM</Copyright>
		<Trademark>RabbitOM™</Trademark>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>
</Project>
