<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<Product>RabbitOM.Player.Decoder</Product>
		<Authors>Rabbit Corp</Authors>
		<Description>Video Decoder</Description>
		<Copyright>Copyright © 2026 RabbitOM</Copyright>
		<Trademark>RabbitOM™</Trademark>
		<MajorVersion>2</MajorVersion>
		<MinorVersion>0</MinorVersion>
		<PatchVersion>9</PatchVersion>
	</PropertyGroup>
</Project>
