using System;

namespace RabbitOM.Streaming.Net.Next.Rtsp
{
    public enum RtspStatusCode
    {
        UnDefined                         = 0,
        Continue                          = 100,
        OK                                = 200,
        Created                           = 201,
        LowOnStorageSpace                 = 250,
        MultipleChoices                   = 300,
        MovedPermanently                  = 301,
        MovedTemporarily                  = 302,
        SeeOther                          = 303,
        NotModified                       = 304,
        UseProxy                          = 305,
        BadRequest                        = 400,
        UnAuthorized                      = 401,
        PaymentRequired                   = 402,
        Forbidden                         = 403,
        NotFound                          = 404,
        MethodNotAllowed                  = 405,
        NotAcceptable                     = 406,
        ProxyAuthenticationRequired       = 407,
        RequestTimeout                    = 408,
        Gone                              = 410,
        LengthRequired                    = 411,
        PreconditionFailed                = 412,
        RequestEntityTooLarge             = 413,
        RequestUriTooLarge                = 414,
        UnSupportedMediaType              = 415,
        ParameterNotUnderstood            = 451,
        ConferenceNotFound                = 452,
        NotEnoughBandwidth                = 453,
        SessionNotFound                   = 454,
        MethodNotValidInThisState         = 455,
        HeaderFieldNotValidForResource    = 456,
        InvalidRange                      = 457,
        ParameterIsReadOnly               = 458,
        AggregateOperationNotAllowed      = 459,
        OnlyAggregateOperationAllowed     = 460,
        UnSupportedTransport              = 461,
        DestinationUnReachable            = 462,
        KeyManagementFailure              = 463,
        InternalServerError               = 500,
        NotImplemented                    = 501,
        BadGateway                        = 502,
        ServiceUnavailable                = 503,
        GatewayTimeout                    = 504,
        VersionNotSupported               = 505,
        OptionNotSupported                = 551,
    }
}
